language: node_js
node_js:
  - "8"
  - "9"
  - "10"
env:
  global:
  - secure: Bi97R694A+0IdxQnXh/J+Rfg9vgFkyWnaXByYg0Vz3BVTrfKkfIikPKos9hU98/6dutV8t/+TOAbV1iG0pCoFzMZ7YibSi6mVHBdd3KHPe/IzaKx7pVJ/QgkGdxAXRhinmudxFenBhoJzL7WM/6d3U3esgjIHqzp6JaqSz3RK+XGnHxjXWvmBKtXI4KtzgVRBgtJ581UTD1YiV4KTQ4vU3HCWriEJSX+6yQGqtrdcmmnCPIvhXZ7hlXkV1t1VPwV3IWkA4EBtBviIyQAuM2Bh+IsXE9MZI7OHzWDD2X6lMUqShPsYz/nR5oMc2yfKa7kmKX5WUWnbh2wXTKbo2p5Hi210mnAqc27OYzKymef4pnlkBqZ3msoHBw2nOrDyO5477qpSxQWKOvkMLuQ/X9J7HXT31ButIH8YJqzFAUwQm7AVW+6A2hp2kF7AOOsO/WuhXjW5SfPWCIF2qFhvrGwWxR5x0bUu8/rLW0urrLFfhNII4tjX76bP092dfyjP9PJHBrNR/DUvZlqBpZkrwtbTBXH5xPtME+cRThElp5ZG9/n1KyZnSPTcN1yDuT1clRleH2A07gwPKKk2RgHv+/UoLh55mW+097f0TP1ILLdJDVhHAn+C0k8Zf5OMWFx0+XOdwXpsaPbTzb/6t59foP80brNkQg4RccT7Y2b8BG4DJ8=
  matrix:
  - TEST_SUITE=lint
  - TEST_SUITE=build
  - TEST_SUITE=unit
  - TEST_SUITE=docs
matrix:
  exclude:
    - node_js: "8"
      env: TEST_SUITE=lint
    - node_js: "8"
      env: TEST_SUITE=docs
    - node_js: "9"
      env: TEST_SUITE=lint
    - node_js: "9"
      env: TEST_SUITE=docs
cache:
  directories:
  - node_modules
  - "$(npm config get prefix)/node_modules"
before_script:
- npm install --no-save @donmahallem/trapeze-api-types
script:
- npm run test:$TEST_SUITE
after_success:
- ./coveralls_upload.sh
jobs:
  include:
  - stage: npm release
    node_js: '10'
    script: npm run build
    if: tag IS present
    deploy:
      provider: npm
      skip_cleanup: true
      email: $npm_email
      api_key: $npm_api_key
      on:
        tags: true
        repo: donmahallem/TrapezeApiClientNode
  - stage: github pages release
    node_js: '10'
    script: npm run docs
    if: branch = master
    deploy:
      provider: pages
      skip-cleanup: true
      local-dir: docs
      github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
      keep-history: true
      on:
        branch: master
