language: node_js
node_js:
  - "8"
  - "9"
  - "10"
env:
  matrix:
  - TEST_SUITE=lint
  - TEST_SUITE=build
  - TEST_SUITE=unit
  - TEST_SUITE=docs
matrix:
  exclude:
    - node_js: "8"
      env: TEST_SUITE=lint
    - node_js: "8"
      env: TEST_SUITE=docs
    - node_js: "9"
      env: TEST_SUITE=lint
    - node_js: "9"
      env: TEST_SUITE=docs
cache: node
before_script:
- npm install --no-save @donmahallem/trapeze-api-types
script:
- npm run test:$TEST_SUITE
after_success:
- ./coveralls_upload.sh
jobs:
  include:
  - stage: Deployment
    node_js: '10'
    script: npm run docs
    deploy:
    - provider: pages
      skip-cleanup: true
      local-dir: docs
      github-token: $GITHUB_TOKEN
      keep-history: true
      on:
        branch: master
    - provider: npm
      skip_cleanup: true
      email: $npm_email
      api_key: $npm_api_key
      on:
        tags: true
        all_branches: true
        repo: donmahallem/TrapezeApiClientNode
